# Generated by Django 4.2.8 on 2023-12-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_class',
            name='role',
            field=models.CharField(max_length=28, null=True),
        ),
    ]
