# Generated by Django 4.2.8 on 2023-12-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_users_class_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_class',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
