# Generated by Django 4.2.8 on 2023-12-09 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_remove_doctor_role_remove_patient_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='date',
            new_name='created_at',
        ),
    ]
