# Generated by Django 4.2.8 on 2023-12-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_medicalreportrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreportrequest',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
